In [4]:
# creating array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.shape) # --> this is single dimensional array

[1 2 3 4 5 6]
(6,)


In [6]:
# changing dimension of array
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
print(np.arange(0,10))
print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [14]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])

print("Array:/n",arr)
print("shape:",arr.shape)
print("number of dimensions:",arr.ndim)
print("size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:/n [[1 2 3 4 5]
 [6 7 8 9 0]]
shape: (2, 5)
number of dimensions: 2
size (number of elements): 10
Data type: int32
Item size (in bytes): 4


In [24]:
# Numpy vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise Addition
print("addition:",arr1+arr2)
# Element wise Subtraction
print("subtraction:",arr1-arr2)
# Element wise Multiplication
print("Multiplication:",arr1*arr2)
# Element wise Divison
print("Division:",arr1/arr2)

addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [29]:
# Universal functions --> function that applies to entire array

arr = np.array([2,3,4])
# Square root function
print(np.sqrt(arr))
# Exponential function
print(np.exp(arr))
# sine function
print(np.sin(arr))
# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.        ]
[ 7.3890561  20.08553692 54.59815003]
[ 0.90929743  0.14112001 -0.7568025 ]
[0.69314718 1.09861229 1.38629436]
